---
title: "Python List Length and Element Checks and Defaults"
titleshort: "List Manipulations and Defaults"
description: |
  Conditional statements based on list length and element value.
  Provide default for element of a list when list does not have that element.
core:
  - package: py
    code: |
      lambda
      join
      append()
      if len(X) >= 3 and X[2] is not None
      if elif else
date: 2020-10-24
date_start: 2020-10-25
output:
  pdf_document:
    pandoc_args: '../../_output_kniti_pdf.yaml'
    includes:
      in_header: '../../preamble.tex'
  html_document:
    pandoc_args: '../../_output_kniti_html.yaml'
    includes:
      in_header: "../../hdga.html"
always_allow_html: true
urlcolor: blue
---

### List

```{r global_options, include = FALSE}
try(source("../../.Rprofile"))
```

`r text_shared_preamble_one`
`r text_shared_preamble_two`
`r text_shared_preamble_thr`

```{python}
import numpy as np
```

#### Loop Through a List get Value and Index 

There is a list, loop through it, get out both the index and the value of each indexed element together. 

```{python}
ls_ob_combo_type = ["e", "20201025x_esr_list_tKap_mlt_ce1a2", ["esti_param.kappa_ce9901", "esti_param.kappa_ce0209"], 1, "C1E31M3S3=1"]
for it_idx, ob_val in enumerate(ls_ob_combo_type):
    print(f'{it_idx=} and {ob_val=}')
```

#### Parse Elements of a List 

A list has multiple elements, deal them out.

```{python}
list_test = ['C1E126M4S3', 2]
[compesti_short_name, esti_top_which] = list_test
print(f'{compesti_short_name=} and {esti_top_which=}')
```

#### Check if Any Element of a List is another List

There is a list with two elements, there is another list with say four elements. Check if any of the two element is in the list with four elements. 

```{python}
ar_int_list_a1 = [1,2]
ar_int_list_a2 = [2,1111]
ar_int_list_a3 = [2111,1111]
ar_int_list_b = [1,2,3,11,999]
ar_int_list_c = [2]

check_any_a1_in_b =  any(item in ar_int_list_a1 for item in ar_int_list_b)
check_any_a2_in_b =  any(item in ar_int_list_a2 for item in ar_int_list_b)
check_any_a3_in_b =  any(item in ar_int_list_a3 for item in ar_int_list_b)
check_any_a1_in_c =  any(item in ar_int_list_a1 for item in ar_int_list_c)

print(f'{check_any_a1_in_b=}')
print(f'{check_any_a2_in_b=}')
print(f'{check_any_a3_in_b=}')
print(f'{check_any_a1_in_c=}')
```

#### Convert a List to a String List

Given a list of string and numeric values, convert to a list of string values. The MAP function is like [apply](https://fanwangecon.github.io/R4Econ/function/noloop/htmlpdfr/fs_apply.html) in R.

- [How to concatenate items in a list to a single string?](https://stackoverflow.com/a/34011944/8280804)

```{python}
ls_spec_key = ['ng_s_d', 'esti_test_11_simu', 2, 3]
ls_st_spec_key = list(map(str, ls_spec_key))
print(ls_st_spec_key)
```

Additionally, append some common element to each element of the string using MAP.

```{python}
ls_spec_key = ['ng_s_d', 'esti_test_11_simu', 2, 3]
ls_st_spec_key = list(map(lambda x: 'add++' + str(x), ls_spec_key))
print(ls_st_spec_key)
```

Equivalently, via list comprehension

```{python}
ls_spec_key = ['ng_s_d', 'esti_test_11_simu', 2, 3]
ls_st_spec_key = ['list_comprehension' + str(spec_key) for spec_key in ls_spec_key]
print(ls_st_spec_key)
```

#### Concatenate a List to a String with Separator

Given a list of strings and numeric data types, concatenate list to a string with some separator. Also in reverse, generate a list by breaking a string joined by some separator. 

```{python}
ls_spec_key = ['ng_s_d', 'esti_test_11_simu', 2, 3]
st_separator = '='
st_spec_key = st_separator.join(list(map(lambda x : str(x), ls_spec_key)))
print(st_spec_key)
```

Now break string apart:

```{python}
st_spec_key = '='.join(list(map(lambda x : '$' + str(x) + '$', ['ng_s_d', 'esti_test_11_simu', 2, 3])))
print(st_spec_key.split('='))
```

#### Add Nth Element to List when Nth Element Does not Exist

There is a list with 2 elements, check if the list has 3 elements, if not, add another element. 

```{python}
ls_string_A = ['c', '20180918']
ls_string_B = ['c', '20180918', ['esti_param.alpha_k']]

for ls_string in [ls_string_A, ls_string_B]:
  if len(ls_string) == 2:
    ls_string.insert(2, None)
    
  print(ls_string)
  
```

#### Check If List Has N Elements of None for Some Elements

In the example below, for A, B and C, do something, for D and E do something else.

```{python}
ls_string_A = ['c', '20180918']
ls_string_B = ['c', '20180918', None]
ls_string_C = ['c', '20180918', None, None]
ls_string_D = ['c', '20180918', ['esti_param.alpha_k'], None]
ls_string_E = ['c', '20180918', ['esti_param.alpha_k'], 5]

for ls_string in [ls_string_A, ls_string_B, ls_string_C, ls_string_D, ls_string_E]:
  if len(ls_string) >= 3 and ls_string[2] is not None:
    print(ls_string)
  else:
    print(ls_string[0:2])
  
```

#### Add a Default Value to Nth Element of List

There is a string list with potential potentially three elements. But sometimes the input only has two elements. Provide default third element value if third element is NONE or if the string list only has two elements.

```{python}

ls_string_A = ['c', '20180918']
ls_string_B = ['c', '20180918', None]
ls_string_C = ['c', '20180918', ['esti_param.alpha_k']]

for ls_string in [ls_string_A, ls_string_B, ls_string_C]:

  if len(ls_string) <= 2:
    # Deals with situation A
    ls_string.append(['esti_param.alpha_k'])
  elif ls_string[2] is None:
    # Deals with situation B
    ls_string[2] = ['esti_param.alpha_k']
  else:
    # Situation C
    pass

  print(ls_string)
```


Now do the same thing for a numeric list:

```{python}

ls_string_A = [11, 22]
ls_string_B = [11, 22, None]
ls_string_C = [11, 22, 33]

for ls_string in [ls_string_A, ls_string_B, ls_string_C]:

  if len(ls_string) <= 2:
    # Deals with situation A
    ls_string.append(33)
  elif ls_string[2] is None:
    # Deals with situation B
    ls_string[2] = 33
  else:
    # Situation C
    pass

  print(ls_string)
```
