---
title: "Data Structures and Cloud Services with Python"
author: "Fan Wang"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Python Implementation Examples for Research Tasks"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    pandoc_args: '_output_kniti_pdf.yaml'
    includes:
      in_header: 'preamble_book.tex'
  html_document:
    pandoc_args: '_output_kniti_html.yaml'
always_allow_html: true
github-repo: fanwangecon/R4Econ
---

```{r global_options, include = FALSE}
source(".Rprofile")
```

# Preface {-}

`r text_top_count`

The work-in-progress [Py4Econ](https://github.com/FanWangEcon/Py4Econ) python examples repository.

> [**bookdown site**](https://fanwangecon.github.io/Py4Econ/bookdown) and [**bookdown pdf**](https://fanwangecon.github.io/Py4Econ/bookdown/Data-Structures-and-Cloud-Services-with-Python.pdf).

Files are written with [RMD](https://rmarkdown.rstudio.com/). Materials are gathered from various [projects](https://fanwangecon.github.io/research) in which python code is used for research and paper-administrative tasks. Bullet points show which python packages/functions are used to achieve various objectives. This is not a python package, but a set of example files. The [pyfan](https://pyfan.readthedocs.io/en/latest/) package repository provides some associated programs.

Other repositories: For dynamic savings problems, see [MEconoTools](https://fanwangecon.github.io/MEconTools/); For code examples, see also [Matlab Example Code](https://fanwangecon.github.io/M4Econ/),  [R Example Code](https://fanwangecon.github.io/R4Econ/), and [Stata Example Code](https://fanwangecon.github.io/Stata4Econ/); For intro econ with Matlab, see [Intro Mathematics for Economists](https://fanwangecon.github.io/Math4Econ/), and for intro stat with R, see [Intro Statistics for Undergraduates](https://fanwangecon.github.io/Stat4Econ/). See [here](https://github.com/FanWangEcon) for all of [Fan](https://fanwangecon.github.io/)'s public repositories.

The site is built using [Bookdown](https://bookdown.org/) [@R-bookdown].

Please contact [FanWangEcon](https://fanwangecon.github.io/) for issues or problems.

`r text_end_count`
